**이름: 손민아**

# 'preprocessing.csv'파일은 온라인 쇼핑몰 고객들의 정보가 들어있다. Online Shopper인지 여부를 예측하기 위하여 머신러닝 알고리즘을 적용하려고 한다. 다음의 전처리 과정을 수행하여라.

In [ ]:
# libraries
import numpy as np # used for handling numbers
import pandas as pd # used for handling the dataset
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling

## 1. 데이터프레임으로 csv파일을 불러와서 특성 행렬 X와 타깃 벡터 Y로 분리하라.

In [ ]:
dataset = pd.read_csv('preprocessing.csv') 

In [ ]:
dataset

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [ ]:
X = ???
Y = ???

In [ ]:
X, Y

(   Region   Age   Income
 0   India  49.0  86400.0
 1  Brazil  32.0  57600.0
 2     USA  35.0  64800.0
 3  Brazil  43.0  73200.0
 4     USA  45.0      NaN
 5   India  40.0  69600.0
 6  Brazil   NaN  62400.0
 7   India  53.0  94800.0
 8     USA  55.0  99600.0
 9   India  42.0  80400.0, 0     No
 1    Yes
 2     No
 3     No
 4    Yes
 5    Yes
 6     No
 7    Yes
 8     No
 9    Yes
 Name: Online Shopper, dtype: object)

## 2. Age, Income의 결측치에 대해 평균값으로 대체하라.

In [ ]:
# handling the missing data and replace missing values with nan from numpy and replace with mean of all the other values
imputer = SimpleImputer(???) 
imputer = imputer.fit(???)
X.iloc[:, 1:] = imputer.transform(???)

In [ ]:
X

Region        Age        Income
0   India  49.000000  86400.000000
1  Brazil  32.000000  57600.000000
2     USA  35.000000  64800.000000
3  Brazil  43.000000  73200.000000
4     USA  45.000000  76533.333333
5   India  40.000000  69600.000000
6  Brazil  43.777778  62400.000000
7   India  53.000000  94800.000000
8     USA  55.000000  99600.000000
9   India  42.000000  80400.000000

## 3. 범주형 특성들에 대해 원핫인코딩하라.

In [ ]:
# encode categorical data
from sklearn.preprocessing import LabelBinarizer, LabelEncoder
labelbinarizer_X = LabelBinarizer()
X_b= labelbinarizer_X.fit_transform(???)
X_with_onehot = np.hstack((X_b,???))
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [ ]:
X_with_onehot, Y

(array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.90000000e+01,
         8.64000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.20000000e+01,
         5.76000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
         6.48000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.30000000e+01,
         7.32000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.50000000e+01,
         7.65333333e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
         6.96000000e+04],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.37777778e+01,
         6.24000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.30000000e+01,
         9.48000000e+04],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 5.50000000e+01,
         9.96000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.20000000e+01,
         8.04000000e+04]]), array([0

## 4. 10개의 샘플 중 8개는 학습 데이터세트, 2개는 테스트세트로 하여 표준화 방법으로 특성행렬을 스케일링하라.

In [ ]:
# splitting the dataset into training set and test set
X_train, X_test, Y_train, Y_test = ???

In [ ]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.90000000e+01,
        8.64000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.20000000e+01,
        5.76000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        6.48000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.30000000e+01,
        7.32000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.50000000e+01,
        7.65333333e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.96000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.37777778e+01,
        6.24000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.30000000e+01,
        9.48000000e+04]])

In [ ]:
# feature scaling
sc_X = ???
X_train = sc_X.fit_transform(X_train) 

In [ ]:
X_train

array([[-0.77459667,  1.29099445, -0.57735027,  0.9919531 ,  1.13089809],
       [ 1.29099445, -0.77459667, -0.57735027, -1.64177922, -1.33030078],
       [-0.77459667, -0.77459667,  1.73205081, -1.17700292, -0.71500106],
       [ 1.29099445, -0.77459667, -0.57735027,  0.06240052,  0.00284861],
       [-0.77459667, -0.77459667,  1.73205081,  0.37225138,  0.28770959],
       [-0.77459667,  1.29099445, -0.57735027, -0.40237577, -0.30480125],
       [ 1.29099445, -0.77459667, -0.57735027,  0.18289808, -0.92010097],
       [-0.77459667,  1.29099445, -0.57735027,  1.61165483,  1.84874777]])